name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ls
      run: |
        ls

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: DockerBuild
      run: |
        tag=$(date +%Y%m%d%H%M)
        image="${{ secrets.DOCKERHUB_USERNAME }}/pgbouncer-ubuntu2204:$tag"
        cd 1/ubuntu-2204/
        ls
        docker build -t $image .
        docker images
        docker push $image
